### ISSUE TITLE
how to set CORS or allow x-Frame-Options

### ISSUE THREAD

**Issue by vsnshanmuganathan** [adrianmusante/docker-pocketbase#3]
I want to embed this in iframe but i get 
`Refused to display "mydomain.com" in  a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by adrianmusante** [comment]
The image of PocketBase used in this repository relies on the original binary files of [PocketBase](https://pocketbase.io/). If this were to become a real issue, please report it to the [pocketbase/pocketbase](https://github.com/pocketbase/pocketbase/issues) repository.

Regardless, I've reviewed it and by default, it doesn't have CORS restrictions. If you'd like, you can try adding the evironment variable `POCKETBASE_OPTS` during docker startup with a value for `--origins`. However, the default value is `*`, so it shouldn't make any difference.

For `X-Frame-Options` header, I found the issue https://github.com/pocketbase/pocketbase/issues/677 but `X-Frame-Options` continue in the response by current version. Maybe, you could be use a reverse proxy for remove this header for paths that you need.

I close the issue because it is not a problem with the docker image that I built. Only the owner of the binary is who could solve it in case of a problem.
